[package]
name = "jeton"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
aho-corasick = "1.1.3"
lazy_static = "1.5.0"
rayon = "1.10.0"
rayon-cond = "0.3.0"
regex = "1.11.1"
serde = { version = "1.0.217", features = ["derive"] }